### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by natanleung** [natanleung/APS360-captcha-bypass#7]
## TODO:

- [x] Hyperparameter tuning
- [x] Remove `Pipfile` and `Pipfile.lock`
> Are these files necessary to run `dataset_generator.py`?
- [ ] Update `README.md` with project description
- [x] Remove old `.ipynb` files that are redundant (Add in Baseline model from captcha.ipynb before doing that)
- [x] Update filename of `alexnet.ipynb` or whichever becomes the final Colab notebook
- [x] Code cleanup within final Colab notebook
> Copy `Base model` into notebook
> Remove unnecessary cells / code blocks
> Comments
- [x] Generate PDF of final Colab run with output and add to repository (`.ipynb` -> `.html` -> `.pdf`, similar to lab assignments)

**Comment by fcpranav** [comment]
`Are these files necessary to run dataset_generator.py?` It makes it easy to setup your environment since you need to install a package dependency.
